export const MONTHLY_SCHEDULE_LIMIT_HOURS = 186;
export const MONTHLY_SCHEDULE_LIMIT_MINUTES =
  MONTHLY_SCHEDULE_LIMIT_HOURS * 60;
export const MONTHLY_SCHEDULE_WARNING_HOURS = 174;
export const MONTHLY_SCHEDULE_WARNING_MINUTES =
  MONTHLY_SCHEDULE_WARNING_HOURS * 60;
